### ISSUE TITLE
Migrate to a mono repo with images-responsiver to ease management?

### ISSUE THREAD

**Issue by nhoizey** [nhoizey/eleventy-plugin-images-responsiver#52]
There's the core feature in [images-responsiver](https://github.com/nhoizey/images-responsiver/) and the plugin for Eleventy here.

Every time the former evolves, this one should too.

It's not easy to manage two repositories for projects so linked together, and probably difficult for users to understand where to open issues.

- What would be the best (and easy) way to manage such a mono repo, with npm releases?
- What would be the best (and easy) way to migrate both current repos into a mono repo?

Help welcome.

**Comment by nhoizey** [comment]
I guess I could have to projects:
- `core`
- `eleventy-plugin`

And then later other projects, maybe `gatsby-plugin` for example…

Does it make sense?

**Comment by shavounet** [comment]
If one commit impacts all dependencies, I'd say yeah, having a monorepo can be really useful. 

I don't know enough about npm to help you there, but about git, I'd say:
- first think about the folder layout you want, I like having a "apps" folder (or any other name) that will contain one subdirectory for every subproject. It should ease npm deployments, sandboxing and tests, and docker manipulation. 
- I don't have the like with me, but there is a `git subtree` command that is especially useful to merge different repositories into a single one. This way you should be able to keep existing commit trees and have a folder layout like the one I mention. Maybe you should start on an orphan branch, and then push it ?

**Comment by nhoizey** [comment]
@shavounet thanks for joining the discussion!

> If one commit impacts all dependencies, I'd say yeah, having a monorepo can be really useful.

Most commits on `images-reponsiver` lead to a new release, which should be used ASAP in `eleventy-plugin-images-responsiver`.

> first think about the folder layout you want, I like having a "apps" folder (or any other name) that will contain one subdirectory for every subproject. It should ease npm deployments, sandboxing and tests, and docker manipulation.

I will indeed have a root folder to "host" the subprojects. 👍

> I don't have the like with me, but there is a git subtree command that is especially useful to merge different repositories into a single one. This way you should be able to keep existing commit trees and have a folder layout like the one I mention. 

Useful commits history is mostly on `images-responsiver`, I don't mind losing the history from `eleventy-plugin-images-responsiver`.

If it's not too difficult to keep the history, I might do it anyway. It looks like [`subrepo`](https://github.com/ingydotnet/git-subrepo) is better than `subtree`: https://delicious-insights.com/en/posts/mastering-git-subtrees/

> Maybe you should start on an orphan branch, and then push it ?

I think I'll probably work on `images-responsiver`'s master branch, to ease keeping its history, but I'll think about it.

**Comment by nhoizey** [comment]
Work started with Lerna in https://github.com/nhoizey/images-responsiver-monorepo

**Comment by nhoizey** [comment]
There is now a `monorepo` branch in https://github.com/nhoizey/images-responsiver/tree/monorepo

**Comment by nhoizey** [comment]
Migration completed!
