### ISSUE TITLE
Conflict with other optimizations?

### ISSUE THREAD

**Issue by dixonge** [nhoizey/eleventy-plugin-images-responsiver#6]
I have three sites at this time. One is not using any optimization, so it's good to go. A second site is using Netlify's 'asset optimization' for images, which I think just compresses them. The third site is using Git LFS.

Will this plugin conflict with or be redundant in any of these scenarios?

**Comment by nhoizey** [comment]
The first site should be greatly improved… 😁

For the second site, using Netlify's asset optimization "only" compresses the images, so there is no risk using the plugin. However, you need to decide how you want resized images to be generated. [Netlify Large Media](https://www.netlify.com/products/large-media/) can do that, but I never tried.

For the third site, there should be no problem either, as Git LFS is only for versioned assets storage.

**Comment by dixonge** [comment]
Question was answered. Closing to clean up...
